api_platform:
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        jsonhal: [ 'application/hal+json' ]
        #todo esto de abajo es para que en la parte de autorizathion en api platform nos permita introducir una clave api_key
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header

